from wsgi import app

#THIS CODE CREATE BY @JOBAYAR_AHME
#THIS CODE CREATE BY @JOBAYAR_AHME
#THIS CODE CREATE BY @JOBAYAR_AHME
#THIS CODE CREATE BY @JOBAYAR_AHME
#THIS CODE CREATE BY @JOBAYAR_AHME
#THIS CODE CREATE BY @JOBAYAR_AHME